services:
  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./deploy/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./deploy/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app-network

  webserver:
    container_name: webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
        - 8080:80
    volumes:
        - ./deploy/app.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www
    logging:
        options:
            max-size: "10m"
            max-file: "3"
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./deploy/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

volumes:
  dbdata:
    driver: local


networks:
  app-network:
    driver: bridge